### PR TITLE
fix tributary sync test

### LINKED ISSUE #291: Tributary sync test intermittently fails
https://github.com/serai-dex/serai/actions/runs/4921632496/jobs/8791653466 failed, with the next run passing.

### PR DESCRIPTION
**Pull request by akildemir**
fix https://github.com/serai-dex/serai/issues/291

### CODE REVIEW

File: coordinator/src/tests/tributary/sync.rs [hunk 1]
```diff
@@ -112,21 +114,28 @@ async fn sync_test() {
...
-    {
-      return;
-    }
-    sleep(Duration::from_secs(block_time)).await;
+  // Because only `t` validators are used in a commit, take n - t nodes offline
+  // leaving only `t` nodes. Which should force it to participate in the consensus
+  // of next blocks.
+  let n = (spec.n() - spec.t()) as usize;
+  for t in p2p_threads.iter().take(n) {
+    t.abort();
```
Comment (kayabaNerve) [inline coordinator/src/tests/tributary/sync.rs:122]: I'd prefer
```
  let spares = usize::from(spec.n() - spec.t());
  for thread in p2p_threads.iter().take(spares) {
    thread.abort();
```

`as` violates safety, and then you call this `n` when it isn't `n`. It's `n-t`. Then the usage of a variable, `t`, for a thread when `t` already exists is in conflict. But it's not worth blocking the merge for if tests pass.

**Comment by kayabaNerve** [comment]
Even if this doesn't consistently work, it is a tighter test and appreciated accordingly.
